Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -285,13 +285,6 @@ cd $BUILD_DIR
 curl https://busybox.net/downloads/busybox-1.29.2.tar.bz2  --output busybox.tar.bz2
 mkdir busybox && tar xjvf busybox.tar.bz2 -C busybox
 
-# Install VIM
-cd $BUILD_DIR
-rm -R vim
-curl https://s3.amazonaws.com/heroku-jvm-buildpack-vi/vim-7.3.tar.gz --output vim.tar.gz
-mkdir vim && tar xzvf vim.tar.gz -C vim
-export PATH=$PATH:/app/vim/bin
-
 # Install SQLite
 cd $BUILD_DIR
 npm install --save sqlite3
@@ -312,6 +305,54 @@ cd webdis
 make
 
 cd $BUILD_DIR
+
+
+
+# Install VIM
+#cd $BUILD_DIR
+#rm -R vim
+#curl https://s3.amazonaws.com/heroku-jvm-buildpack-vi/vim-7.3.tar.gz --output vim.tar.gz
+#mkdir vim && tar xzvf vim.tar.gz -C vim
+#export PATH=$PATH:/app/vim/bin
+## Configure environment (fail test)
+set -e
+
+## Buildpack directory
+readonly BP_DIR=$(cd "$(dirname "${0:-}")"/..; pwd) # absolute path
+
+readonly BUILD_DIR="${1:-}"
+readonly CACHE_DIR="${2:-}"
+
+VIM_FILENAME='vim-static.tar.gz'
+AMZ_VIM_URL="https://s3.amazonaws.com/bengoa/$VIM_FILENAME"
+
+echo "    -> Downloading VIM... (${AMZ_VIM_URL})"
+
+curl --retry 2 --silent --max-time 60 --location "${AMZ_VIM_URL}" --output "${CACHE_DIR}/${VIM_FILENAME}"
+
+# install
+echo "    -> Installing VIM..."
+
+mkdir -p "$BUILD_DIR/vim"
+tar -xf "${CACHE_DIR}/${VIM_FILENAME}" -C "${BUILD_DIR}/vim"
+
+# export
+PROFILE_PATH="$BUILD_DIR/.profile.d/vim.sh"
+mkdir -p $(dirname $PROFILE_PATH)
+echo 'export PATH=$PATH:/app/vim' >> $PROFILE_PATH
+
+echo "    DONE"
+
+
+
+
+
+
+
+
+
+
+
 
 header "Build succeeded!"
 mcount "compile"
